package br.com.reqs.already.api.v1.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2021-03-13T21:52:20.319-03:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://ws.v1.api.already.reqs.com.br/", name = "PedidoWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface PedidoWS {

    @WebMethod
    @Action(input = "http://ws.v1.api.already.reqs.com.br/PedidoWS/criarPedidoRequest", output = "http://ws.v1.api.already.reqs.com.br/PedidoWS/criarPedidoResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.v1.api.already.reqs.com.br/PedidoWS/criarPedido/Fault/AuthorizationException")})
    @WebResult(name = "criarPedidoResponse", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", partName = "result")
    public CriarPedidoResponse criarPedido(
        @WebParam(partName = "parameters", name = "criarPedido", targetNamespace = "http://ws.v1.api.already.reqs.com.br/")
        CriarPedido parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", header = true)
        Token token
    ) throws AuthorizationException;

    @WebMethod
    @Action(input = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidosRequest", output = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidosResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidos/Fault/AuthorizationException")})
    @WebResult(name = "getPedidosResponse", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", partName = "result")
    public GetPedidosResponse getPedidos(
        @WebParam(partName = "parameters", name = "getPedidos", targetNamespace = "http://ws.v1.api.already.reqs.com.br/")
        GetPedidos parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", header = true)
        Token token
    ) throws AuthorizationException;

    @WebMethod
    @Action(input = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidoByIdRequest", output = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidoByIdResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.v1.api.already.reqs.com.br/PedidoWS/getPedidoById/Fault/AuthorizationException")})
    @WebResult(name = "getPedidoByIdResponse", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", partName = "result")
    public GetPedidoByIdResponse getPedidoById(
        @WebParam(partName = "parameters", name = "getPedidoById", targetNamespace = "http://ws.v1.api.already.reqs.com.br/")
        GetPedidoById parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", header = true)
        Token token
    ) throws AuthorizationException;

    @WebMethod
    @Action(input = "http://ws.v1.api.already.reqs.com.br/PedidoWS/removerPedidoRequest", output = "http://ws.v1.api.already.reqs.com.br/PedidoWS/removerPedidoResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.v1.api.already.reqs.com.br/PedidoWS/removerPedido/Fault/AuthorizationException")})
    @WebResult(name = "removerPedidoResponse", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", partName = "result")
    public RemoverPedidoResponse removerPedido(
        @WebParam(partName = "parameters", name = "removerPedido", targetNamespace = "http://ws.v1.api.already.reqs.com.br/")
        RemoverPedido parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", header = true)
        Token token
    ) throws AuthorizationException;

    @WebMethod
    @Action(input = "http://ws.v1.api.already.reqs.com.br/PedidoWS/atualizarPedidoRequest", output = "http://ws.v1.api.already.reqs.com.br/PedidoWS/atualizarPedidoResponse", fault = {@FaultAction(className = AuthorizationException.class, value = "http://ws.v1.api.already.reqs.com.br/PedidoWS/atualizarPedido/Fault/AuthorizationException")})
    @WebResult(name = "atualizarPedidoResponse", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", partName = "result")
    public AtualizarPedidoResponse atualizarPedido(
        @WebParam(partName = "parameters", name = "atualizarPedido", targetNamespace = "http://ws.v1.api.already.reqs.com.br/")
        AtualizarPedido parameters,
        @WebParam(partName = "token", name = "token", targetNamespace = "http://ws.v1.api.already.reqs.com.br/", header = true)
        Token token
    ) throws AuthorizationException;
}
